### ISSUE TITLE
Delivery timer

### ISSUE THREAD

**Issue by Androwski3000** [LukeMarlin/factorio-logistic-request-hinter#3]
Hi,
I like the idea of the mod.
Could there be a timer added for when:
-the first item arrives,
-the last item arries.

I play the Pyanodon mods alot. The bases get big fast there. But bot speed research is not easy to access, as science pack 3 and 4 require huge factories, which need alot of time to build.
And the player has to wait alot for items to arrive, delivered by bots. 
It would be very useful to know, when waiting time ends.

**Comment by LukeMarlin** [comment]
Hi there and thank you for your interest!

To be honest, I've been pondering this feature after using the mod on my game. My bots are usually busy for many reasons and this is indeed frustrating not to know how much time you'll have to wait.

However, This task seems really complex, here's a few things to consider to get a timer:

- Are there bots available? If not, when will they be?
- Which bot is going to take your request?
- Which request is going to be selected first?
- Which chest will it reach?
- Will he need to replenish batteries on the way?

As for number 1, this would require answering questions 2, 3, 4 and 5 for every other requests of all players (including you).

I would say that the best I can provide (with some work) would be an estimated delivery time for the items that are already on their way, which wouldn't provide a full answer...

I'll leave that open for now but I'm not sure we can find a way to do it :disappointed:

**Comment by LukeMarlin** [comment]
Well, asking these points to devs led me to this:

> Klonan Today at 11:20 AM
> I don't think even the base game has the answers
> bots just do their own thing

I'll try to look at this during Christmas anyway

**Comment by Androwski3000** [comment]
Hi,
what you try to do is make it absolutely perfect by considering everything.
Maybe the approach for the timer can be simplified.

It sometimes helps to know if the item is on it´s way or not. As you can consider to take a car or a train back to pick it up by yourself.

It would be enough to show that a bot is on its way to pick up an item with a timer. You then know, when it is on it´s way to you.
The GUI of the mod shows that with a "on my way to pick up-Icon" - [TIMER]. 

After the bot picked the item up, it is on it´s way to you. 
The GUI of the mod shows that with a "on my way to pick to you-Icon" - [TIMER]. 

Time for recharging could not be considered.
Every bot has a maximum flight time before he needs to recharge. If the maximum delivery time is higher than the flight time, the timer could be like:
"on my way to pick to you-Icon" - [TIMER+]

So the timer can still show the ideal flight time as if the bot would never reload. Like: distance / speed = time. If the bot suddenly is on its way to recharge the timer can also count up again, if the measured distance get´s longer.

Let´s say max flight time is 30 sec.:
mm:sec
- 00:26
- 00:38+

Features of the interface:
1. item is on it´s way Yes / no
2. item will be picked up
3. item is on it´s way to player

Example with ASCI:

Legend:
.(8) - picture of item 1 (belt, box, splitter, you name it)
.> - indicator, depending on it´s position, it shows if  a bot is on it´s way to pickup, or if a bot is on it´s way to you.

(8) - xx:xx
item was not queued yet

(8) - > 00:47+
item 1 get´s picked up in 47 sec+ by a bot

(8) - 00:34+>
item is on its way to player and arrives in 34+ seconds

(8) - 00:10>
item is on its way to player and arrives in 10 seconds

(8) - !!:!!
item request fullfilled


This could be further enhanced for the last item of the request. Like with adding a second timer for the last item.
Ingame I just needed four buildings an hour ago. PYmod adds alot of different buildings. The PYmod mall for PYmod buildings is bigger than the vanilla mall.
I only knew that I requested something. I did not knew when the first of the 4 arrives. After arrival of the 1st item, I did not knew, when the 4th one arrives.
As I still only have science pack 2, bots are slow.

**Comment by LukeMarlin** [comment]
Thanks for the detailed input.

A simplified way was indeed my intention when I mentioned looking into it during christmas holidays.
Since there are multiple items per stack, I'm not sure yet how it is possible without a complicated UI to show first & last item status + timer. it's quite a lot of informations:

(8) f<, l> 00:12 00:50+

Showing this all would multiply the UI size by 3 at least so obviously choices are to be made, or we would need a better way to express that. especially since this should work top & left, and that once you reach the end game you might have multiple rows of requests shown.

Maybe showing only "next incoming item", either for a stack or each stack, dumping the minutes (if > 99 seconds just show XX).

If you have any other ideas to dump before the holidays, they are welcome :)

**Comment by Androwski3000** [comment]
I´m glad to add to this mod. I want and dream about this feature every time I wait for delivery. If you are the brain to make this happen, I´m having alot of fun being the dreamer, about how this could work out. :-)

Position wise:
Top left is already used well. With like Helmod, FNEI and others. I would suggest to snap it onto the right, top side, directly to the panel with the map, research bar and so on.
It should be expandable like "Production statistics monitor" with a + icon. So that the screen is not cluttered if you dont need the arrival infos.
So when made small, you only see the +. You could make your + different from "Production statistics monitor". To brand the work ;-) and for recognition.

https://mods.factorio.com/mod/production-monitor
The first picture shows the + that I mean.

Yes. A row of logistic request slots has 6 slots. You can have 3 rows in vanilla or more. With mods one can have maybe even more rows.
So with 3 rows it is 18 lines of items. Thoose who are not delivered, because 100 of 100 requested are arrived, could be not shown.
So you only can see what is "in the air" right now. If the player uses 1 belt, and the counter goes from 99 of 100, the line for the belt pops into the UI.

You are right, seconds is enouth. Minutes can be deleted in mm:ss. Seconds can maybe be done like sss then. So that from going from 101 to 99 seconds or from 10 to 9, the UI does not jump around. Because spaces between number and overall length of text has changed.

**Comment by LukeMarlin** [comment]
There's only three options for position of mod GUI: top, left, center. Center being out of the question, I've included both top & left (you can change that as well as column count  in the settings menu).

That's why I said that the chosen solution should apply to both.

While I like the "+" idea, I'd rather keep the UI "always open" as it is (only icons & colors, it's quite small already), and use the + to add timers.

What do you think?

Also, fulfilled requests are already hidden because there's no point seeing them!

**Comment by Androwski3000** [comment]
I have tested your mod since that last message for the first time. I now know better what is there already.

The time information could be provided as a mouse over function. The UI you have is already good, small, nice and efficient.

**Comment by LukeMarlin** [comment]
It's been a long time. I've been checking with some devs at the time and it was quite clear that no API currently existed to get this information. I don't think this changed since, so this pretty much still isn't doable in a reasonable way, sorry! :(
