### ISSUE TITLE
Crash when setting logistic request (Factorio 0.17.43)

### ISSUE THREAD

**Issue by minyan** [LukeMarlin/factorio-logistic-request-hinter#6]
Error while running event LogisticRequestHinter::on_tick (ID 0)
real number expected got nil.
stack traceback:
	__LogisticRequestHinter__/control.lua:102: in function 'process_player'
	__LogisticRequestHinter__/control.lua:150: in function <__LogisticRequestHinter__/control.lua:147>
stack traceback:
	[C]: in function 'get_inventory'
	__LogisticRequestHinter__/control.lua:102: in function 'process_player'
	__LogisticRequestHinter__/control.lua:150: in function <__LogisticRequestHinter__/control.lua:147

**Comment by LukeMarlin** [comment]
I'll publish the fix for Factorio > 17.35 tonight, it should solve this issue

**Comment by LukeMarlin** [comment]
This is fixed with PR #5
